# Generated by Django 5.1.3 on 2024-11-10 09:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image_url', models.URLField()),
                ('rarity', models.CharField(choices=[('C', 'Common'), ('R', 'Rare'), ('SR', 'Super Rare'), ('SSR', 'Supreme Rare')], max_length=3)),
                ('rarity_rate', models.FloatField()),
                ('style_prompt', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.CharField(max_length=255)),
                ('token_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('is_nft', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
