# Generated by Django 5.1.3 on 2024-11-10 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_card_generator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='is_nft',
        ),
        migrations.RemoveField(
            model_name='card',
            name='token_id',
        ),
        migrations.AlterField(
            model_name='card',
            name='image_url',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='card',
            name='rarity',
            field=models.CharField(max_length=10),
        ),
    ]
